### ISSUE TITLE
Implementovat statusy soutěžících

### ISSUE THREAD

**Issue by harastaivan** [harastaivan/tcup-client#124]
### TODO

- [x] implementovat po #123 
- [x] select dny
- [x] template tabulka
- [x] get statuses
- [x] update status
- [x] reset statuses
- [x] reset pri mountu
- [x] rozdelit admin/user
- [x] loading
- [x] pridat default den (dneska)
- [x] nezobrazovat budouci dny?
- [x] radit podle startNumber
- [x] version bump
- [x] preklady
- [x] ~~rozdelit na klub/kombi?~~

```text
CompetitorStatus
----------------
day: CompetitionDay
pilot: Registration
status: 'DNF' | 'FLYING' | 'OUTLANDING' | 'BACK' (default 'DNF')
```
